### ISSUE TITLE
关于AFGCN和ASGCN

### ISSUE THREAD

**Issue by xdcui-nlp** [BinLiang-NLP/InterGCN-ABSA#13]
你好，我看了一下你关于AFGCN的代码，然后比较了ASGCN的代码，发现模型代码是一样的，是我理解有问题吗？还是就是同一个？期待收到你的回复，谢谢！

**Comment by BinLiang-NLP** [comment]
> 你好，我看了一下你关于AFGCN的代码，然后比较了ASGCN的代码，发现模型代码是一样的，是我理解有问题吗？还是就是同一个？期待收到你的回复，谢谢！

您好。AFGCN在模型结构上是跟ASGCN类似的，AFGCN也是在ASGCN之上做的改进。
差别在于构图方式上，AFGCN和ASGCN使用的图信息是不一样的。请参阅[InterGCN-ABSA/generate_focused_graph.py](https://github.com/BinLiang-NLP/InterGCN-ABSA/generate_focused_graph.py)相关代码。
如有问题请随时联系我。谢谢！！！

**Comment by xdcui-nlp** [comment]
> > 你好，我看了一下你关于AFGCN的代码，然后比较了ASGCN的代码，发现模型代码是一样的，是我理解有问题吗？还是就是同一个？期待收到你的回复，谢谢！
> 
> 您好。AFGCN在模型结构上是跟ASGCN类似的，AFGCN也是在ASGCN之上做的改进。 差别在于构图方式上，AFGCN和ASGCN使用的图信息是不一样的。请参阅[InterGCN-ABSA/generate_focused_graph.py](https://github.com/BinLiang-NLP/InterGCN-ABSA/generate_focused_graph.py)相关代码。 如有问题请随时联系我。谢谢！！！

好的，谢谢！
